version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9821
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    image: sagarchavan9821/disease-fastapi:latest   
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  streamlit:
    image: sagarchavan9821/disease-streamlit:latest 
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi

volumes:
  postgres_data: